//
//  UserDefaultConstants.h
//  MoGO
//
//  Created by 0weislow on 24.01.13.
//
//

#define UD_SAVE_TO_CALENDAR  @"SAVE_TO_CALENDAR"
#define UD_SAVE_PASSWORD  @"SAVE_PASSWORD"
#define UD_USER_NAME  @"USER_NAME"
#define UD_USER_SURNAME  @"USER_SURNAME"
#define UD_USER_STREET  @"USER_STREET"
#define UD_USER_STREET_NR  @"USER_STREET_NR"
#define UD_USER_ZIP  @"USER_ZIP"
#define UD_USER_TOWN  @"USER_TOWN"
#define UD_USER_INSURANCE @"USER_INSURANCE"
#define UD_USER_BIRTHDATE @"USER_BIRTHDATE"


